version: '2.4.{build}'

# branches to build
branches:
  # whitelist
  only:
    - master

image:
- Visual Studio 2017

environment:
  matrix:
    - platform: x64
      configuration: Debug

    - platform: x64
      configuration: Release

# clone directory
clone_folder: c:\projects\DiligentSamples

install:
  # clone submodules
  - git submodule update --init --recursive
  - git clone https://github.com/DiligentGraphics/DiligentCore.git ../DiligentCore --recursive
  - git clone https://github.com/DiligentGraphics/DiligentTools.git ../DiligentTools --recursive
  - git clone https://github.com/DiligentGraphics/DiligentFX.git ../DiligentFX --recursive
  - ..\DiligentCore\BuildTools\Scripts\appveyor\install.bat

before_build:
  - cd c:\projects\DiligentSamples\BuildTools\FormatValidation
  - validate_format_win.bat
  - cd c:\projects
  - echo cmake_minimum_required(VERSION 3.6) > CMakeLists.txt
  - echo Project(DiligentSamples_Test) >> CMakeLists.txt
  - echo add_subdirectory(DiligentCore) >> CMakeLists.txt
  - echo add_subdirectory(DiligentTools) >> CMakeLists.txt
  - echo add_subdirectory(DiligentFX) >> CMakeLists.txt
  - echo add_subdirectory(DiligentSamples) >> CMakeLists.txt
  - echo %PLATFORM%
  - cmake -S . -B ./build -G "Visual Studio 15 2017" -A %PLATFORM%

build:
  project: c:\projects\build\DiligentSamples_Test.sln
  verbosity: minimal
  parallel: true

test_script:
  - 'cd %APPVEYOR_BUILD_FOLDER%\Tests\GoldenImages'
  - run_tests.bat c:\projects\build
